### ISSUE TITLE
How do you specify target area?

### ISSUE THREAD

**Issue by denisecase** [denisecase/rfp-hunt#1]
How many points?
Contiguous?
Is there a limit to points?
Simple? 
Complex?
Point + radius (a circle)?
Two points (a rectangle)? (this can still be challenging....)
Other options?
Infinite points?

**Comment by Charles-Hoot** [comment]
GPS-enabled smartphones are typically accurate to within a 4.9 m (16 ft.) radius under open sky. However, their accuracy worsens near buildings, bridges, and trees.

https://www.gps.gov/systems/gps/performance/accuracy/#how-accurate

**Comment by denisecase** [comment]
Critical information.  We'll start with all locations defined as a Longitude and Latitude with a default radius of 16 ft.  Later, we could make the radius adjustable - and might permit additional location shapes.
