### ISSUE TITLE
Are teams intended to be long term entities

### ISSUE THREAD

**Issue by Charles-Hoot** [denisecase/rfp-hunt#10]
Do we keep teams around or associate them with a competition?
How long are they live and how much can they changed... presumably once the competition starts they can not be modified.

**Comment by denisecase** [comment]
Right now, teams live outside a competition, so they could be long-term entities (e.g 4-6 months or each semester). That would allow the same set of teams to compete more than once per semester, which seems reasonable. 
Correct - active teams (teams playing an active competition) should be locked from editing during the entire competition.
