### ISSUE TITLE
How will clues be given

### ISSUE THREAD

**Issue by Charles-Hoot** [denisecase/rfp-hunt#7]
Clues could consist of text or images.
Hints could be provided in the form of
* extra clues
* hotter/colder background color
* Directional arrow
* Geiger counter style clicks.

If teams use hints, should consider how this affects their score.

**Comment by denisecase** [comment]
Good point!  We will start with 3 clues in order. Each is a string.  Later, we could add an image to a string clue.  
Still later we could vary the number between 2 and N. 
We will also start with warm and hot colors. 
The additional suggestions are very interesting - we may want to enable additional options in GDP 2?
