### ISSUE TITLE
Will there be a leader board

### ISSUE THREAD

**Issue by Charles-Hoot** [denisecase/rfp-hunt#8]
Will players be able to see other scores?  May want to mask the names of the other teams until the competition is over.  Might want to stop updating as the end approaches

**Comment by Vishalreddy114** [comment]
As soon as the competetion ends players will be provided with leaderboards so that they can know where they stands in the competition.

**Comment by denisecase** [comment]
It's mostly cooperative fun, so I don't think a typical leaderboard is needed, but in GDP 2, we could add rankings for number of quests created, number of competitions played, etc?
